controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Product;
use yii\helpers\Url;
use app\models\Feedback;
use yii\helpers\Html;
use yii\grid\GridView;
use app\models\FeedbackSearch;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {   //אם כן מחובר עובר לבית
            return $this->goHome();
        }

        $model = new LoginForm(); // לוגין פרום הוא מחלקה אחרת
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            // . מפעילים על לוגאין פרום 2 שיטות- לאוד ולוגאין. הפונקציה לאוד מעבירה את הפרטים שקיבלנו מהויו ללוגאיןפרום
            Yii::$app->setHomeUrl(Url::to(['article/index'])); // אם הצליח לעשות לוג אין הוא ייכנס לדף אינדקס
            return $this->goBack(); 
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
/*
    public function actionHello()
    {
        return $this->render('hello');
    }

    public function actionProduct()
    {
        return $this->render('product');
    }
    public function actionProductsingle($id){
        return $this->render('productSingle',
        ['model' => Product::findOne($id)
        ]);
    }   
*/
    public function actionFeedback()
    {
        if (\Yii::$app->user->can('admin'))  
        {
            $searchModel = new FeedbackSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams); //כל הפרמטרים מה url
           
            return $this->render('feedback', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider, 
                ]);
         ?>
 
        <?php
        }
        else{    
            $model = new Feedback();
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                Yii::$app->session->setFlash('FeedSubmitted');

                return $this->render('feedback', [
                'model' => $model,        
                ]);
                }
                else {
                    return $this->render('feedback', [
                    'model' => $model,      
            ]);
                    }
        }
    }
}

controllers/TagController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Tag;
use app\models\TagSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\filters\VerbFilter;
use yii\web\response;
use yii\filters\AccessControl;

/**
 * TagController implements the CRUD actions for Tag model.
 */
class TagController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],

            'access' => [ // כאן מגדירים למי מותר להיכנס לאן
                'class' => AccessControl::className(),
                'only' => ['index','view','update','create','delete'], 
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index','view','update','create','delete'], 
                        'roles' => ['manageTags'], 
                    ],
                ],
        ],
        ];
    }

    /**
     * Lists all Tag models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TagSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tag model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tag model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Tag();

      //  if (\Yii::$app->user->can('manageTags',['tag' => $model])){
        
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }

            return $this->render('create', [
                'model' => $model,
            ]);
      //  }
      //  throw new ForbiddenHttpException('Sorry, you are not allowed to add tags');       
    }

    /**
     * Updates an existing Tag model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
 //       if (\Yii::$app->user->can('manageTags')){
            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }

            return $this->render('update', [
                'model' => $model,
            ]);
    //    }
   //     throw new ForbiddenHttpException('Sorry, you are not allowed to update tags');
    }

    /**
     * Deletes an existing Tag model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
 //       if (\Yii::$app->user->can('manageTags')){
            $this->findModel($id)->delete();

            return $this->redirect(['index']);
   //    }
 //   throw new ForbiddenHttpException('Sorry, you are not allowed to delete tags');
    }



    // actionList to return matched tags
    public function actionList($query) //הדולר קווארי מקבל אוסף של תווים, אנו נפנה לדטה בייס  כדי לשלוף תגיות שמתאימות לתווים.
    {                                       // צריכה להיות התאמה בין הדולר קווארי לבין מה שנכתב ב url
        $models = Tag::findAllByName($query); // מודל זה כל האובייקטים של התגים. נלך למחלקה טאג ונפעיל עליה פונקציה פיינדאולבייניימ.
                                                //קיבלנו רשימת כל התגים שמתחילים באוסף התווים שנמצא בקווארי. זהו מערך של אובייקטים
        $items = [];                // מערך ריק שבהמשך נוסיף לו איבר כל פעם

        foreach ($models as $model) {
            $items[] = ['name' => $model->name];    // הוספת איבר למערך. הניימ הראשון הוא סטרינג. הניים השני הוא תכונה.
        }
        // We know we can use ContentNegotiator filter
        // this way is easier to show you here :)
        Yii::$app->response->format = Response::FORMAT_JSON; // נרצה שיחזיר בפורמט גייסון ואז יחזיר את מערך האייטמס

        return $items;
    }


    /**
     * Finds the Tag model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tag the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tag::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
public function behaviors()
    {
        return [ // מערך שהאיבר הראשון שלו הוא ורבס
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [ // כאן מגדירים למי מותר להיכנס לאן
                'class' => AccessControl::className(),
                'only' => ['create','delete'], 
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create','delete'], 
                        'roles' => ['manageUsers'], 
                    ],

                  /*  [
                        'allow' => true,
                        'actions' => ['update'],
                        'roles' => ['updateUsers'],
                        'roleParams' => function() {
                            return ['user' => User::findOne(['id' => Yii::$app->request->get('id')])];
                        }
                    ],
*/                ],
        ],
        ];            
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (\Yii::$app->user->isGuest) {
            throw new ForbiddenHttpException('You are not allowed to perform this action.');

        }
        else{
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);}
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if (\Yii::$app->user->isGuest) {
            throw new ForbiddenHttpException('You are not allowed to perform this action.');

        }
        else{
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
        }
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
     //  if (\Yii::$app->user->can('manageUsers')){
  
            $model = new User();

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }

            return $this->render('create', [
                'model' => $model,
            ]);

     //   }
    //   throw new ForbiddenHttpException('Sorry, you are not allowed to create users');
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
//אם האיידי של היוזר המחובר שווה לאיידי של היוזר   
        $us = Yii::$app->user->id;
        if (\Yii::$app->user->can('admin')){
            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }

            return $this->render('update', [
                'model' => $model,
            ]);  
        } else
        if ($us == $id)
        {
            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }

            return $this->render('update', [
                'model' => $model,
            ]);
        }
        else{
            throw new ForbiddenHttpException('You are not allowed to perform this action.');
        }
   //     }
   //     throw new ForbiddenHttpException('Sorry, you are not allowed to update users');
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
       // if (\Yii::$app->user->can('manageUsers')){
    
            $this->findModel($id)->delete();

            return $this->redirect(['index']);
   //      }
   //     throw new ForbiddenHttpException('Sorry, you are not allowed to delete users');

    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    /*
   if (Yii::$app->user->can('aau')) {
    $session = Yii::$app->session->getId();
    $user1->session = $session;
    $user1->save();
    }*/
   
    $id = Yii::$app->user->id; //מקבלים את איידי של המשתמש המחובר

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [

// אם אמת הסוגרים הראשונים בתוקף, אם שקר הסוגריים השניים בתוקף
             Yii::$app->user->isGuest ? ( // אם אורח ייכנס להומ. אם יוזר ייכנס ליוזרס
            ['label' => 'Home', 'url' => ['../index.php']] //מה קורה אם התנאי מתקיים
             ):(
             ['label' => 'Users', 'url' => ['/user/index']] // מה קורה אם התנאי לא מתקיים
             ),

                [
                'label' => 'About',
                'url' => ['/site/about'],
                'visible' => Yii::$app->user->isGuest,
                ],

                
                [
                    'label' => 'Tags',
                    'url' => ['/tag/index'],
                    'visible' => Yii::$app->user->can('editor'),
                ],

                [
                    'label' => 'Categories',
                'url' => ['/category/index'],
                'visible' => Yii::$app->user->can('editor'),
                ],

                ['label' => 'Articles', 'url' => ['/article/index']],

                
                [
                    'label' => 'Feedbacks Of Articles',
                    'url' => ['/article-feedback/index'],
                    'visible' => Yii::$app->user->can('editor'),
                ],
            
                [
                    'label' => 'Feedbacks Of My Articles',
                    'url' => ['/article-feedback/myfeed?author='.$id], //שרשור עם איידי משתמש מחובר
                    'visible' => Yii::$app->user->can('author'),
                ],


            ['label' => 'Feedback', 'url' => ['/site/feedback']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; GI <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>